[package]
name = "tame-gcs"
version = "0.1.0"
authors = ["Embark <opensource@embark-studios.com>", "Jake Shadle <jake.shadle@embark-studios.com>"]
edition = "2018"
description = "A small library with a limited set of Google Cloud Storage operations"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/tame-gcs"
homepage = "https://github.com/EmbarkStudios/tame-gcs"
repository = "https://github.com/EmbarkStudios/tame-gcs"
keywords = ["gcs", "tame", "sans-io", "storage", "gcp"]
readme = "README.md"

[dependencies]
